roles:
- {name: w-full}
- {name: h-full}
- {name: flex}
- {name: flex-1}
- {name: flex-initial}
- {name: no-padding}
- {name: stat-card}
- {name: stat-card-down}
- {name: stat-card-up}
- {name: head-title}
- {name: recent-ticket-card}
- {name: assign-customer-card, components: null}
- {name: assigned}
- {name: add-new-customer-panel}
- {name: all-tickets-card}
- {name: ticket-status-indicator}
- {name: ticket-status-indicator-closed}
- {name: all-tickets-card-selected}
- {name: form-component}
- {name: text-form-component}
- {name: tickets-control-bar}
- {name: items-center}
- {name: muted-dropdown}
- {name: letter-group-letter}
- {name: all-customers-card}
- {name: opened-customer}
- {name: customers-header-bar}
- {name: customers-control-bar}
- {name: ticket-message}
- {name: items-end}
- {name: search-box}
- {name: pill-label}
- {name: bottom-border}
- {name: new-ticket-select-component}
- {name: new-ticket-text-component}
color_scheme:
  colors:
  - {name: White, color: '#E2E8F0'}
  - {name: Primary 100, color: '#CBD5E1'}
  - {name: Primary 200, color: '#94A3B8'}
  - {name: Primary 300, color: '#64748B'}
  - {name: Primary 400, color: '#475569'}
  - {name: Primary 500, color: '#334155'}
  - {name: Primary 600, color: '#1E293B'}
  - {name: Primary 700, color: '#1E293B'}
  - {name: Primary 800, color: '#020617'}
  - {name: Primary 900, color: '#0b0b15'}
  - {name: Secondary 100, color: '#E0F2FE'}
  - {name: Secondary 200, color: '#BFDBFE'}
  - {name: Secondary 300, color: '#93C5FD'}
  - {name: Secondary 400, color: '#93C5FD'}
  - {name: Secondary 500, color: '#60A5FA'}
  - {name: Secondary 600, color: '#3B82F6'}
  - {name: Secondary 700, color: '#075985'}
  - {name: Secondary 800, color: '#1E3A8A'}
  - {name: Secondary 900, color: '#172554'}
  - {name: Grey 050, color: '#e9e8e8'}
  - {name: Grey 100, color: '#d3d2d1'}
  - {name: Grey 200, color: '#a7a4a4'}
  - {name: Grey 300, color: '#7a7776'}
  - {name: Grey 400, color: '#4e4949'}
  - {name: Grey 500, color: '#221c1b'}
  - {name: Grey 600, color: '#1b1616'}
  - {name: Grey 700, color: '#141110'}
  - {name: Grey 800, color: '#0e0b0b'}
  - {name: Grey 900, color: '#070605'}
  - {name: Grey 950, color: '#030303'}
  - {name: Lilac 100, color: '#FAFAF9'}
  - {name: Lilac 200, color: '#F5F5F4'}
  - {name: Lilac 300, color: '#E7E5E4'}
  - {name: Lilac 400, color: '#D6D3D1'}
  - {name: Lilac 500, color: '#A8A29E'}
  - {name: Lilac 600, color: '#78716C'}
  - {name: Lilac 700, color: '#57534E'}
  - {name: Lilac 750, color: '#57534E'}
  - {name: Lilac 800, color: '#44403C'}
  - {name: Lilac 850, color: '#57534E'}
  - {name: Lilac 900, color: '#292524'}
  - {name: Error 100, color: '#fed9d5'}
  - {name: Error 200, color: '#feb2ab'}
  - {name: Error 300, color: '#fd8c82'}
  - {name: Error 400, color: '#fd6558'}
  - {name: Error 500, color: '#fc3f2e'}
  - {name: Error 600, color: '#ca3225'}
  - {name: Error 700, color: '#97261c'}
  - {name: Error 800, color: '#651912'}
  - {name: Error 900, color: '#320d09'}
  - {name: Primary 050, color: '#ebebf0'}
  - {name: Grey 025, color: '#f3f3f3'}
  - {name: Primary 025, color: '#f3f4f8'}
